spring:
  application:
    name: stock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:53332/stockproject
    username: bookmark_admin
    password: sss1234
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC


polygon:
  api:
    key: s8aPL0bOZgDT0EPVTdBeKy_mIEvE9ue6
    url: https://api.polygon.io


finnhub:
  api:
    url: https://finnhub.io/api/v1
    key: d59v4ohr01qu56mv5710d59v4ohr01qu56mv571g